name: env
channels:
      - conda-forge
dependencies:
      - python=3.9
      - pyarrow
      - pandas
      - jupyter
      - pip:
            - scip
            - numpy
            - scikit-learn
            - pyarrow
            - xgboost
            - imbalanced-learn
            - seaborn
            - tifffile
            - zarr
            - aicsimageio
            - aicspylibczi
