version: '3.9'
services:
    jupyter:
        build: 
            context: .
            dockerfile: docker/conda-jupyter-lab-env
        ports:
            - "8888:8888"
            - "8787:8787"
        volumes:
            - .:/app
            - /data/Experiment_data:/data
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment: 
            - DISPLAY=${DISPLAY}
