ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "SCIP use case workflows"
  site-url: "https://maximlippeveld.github.io/scip-workflows/"
  description: ""
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/mlippeve/ehv/tree/master/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/mlippeve/ehv/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
