name: env
channels:
    - conda-forge
    - fastai
dependencies:
    - python=3.9
    - pyarrow
    - pandas
    - jupyter
    - scanpy
    - python-igraph
    - leidenalg
    - pip:
        - scip[czi]==0.1.11rc3
        - numpy
        - scikit-learn
        - pyarrow
        - xgboost
        - imbalanced-learn
        - seaborn
        - tifffile
        - zarr
        - aicsimageio
        - aicspylibczi
        - flowutils
        - kneed
        - scip-workflows
